### ISSUE TITLE
[BUG] Codex crash on aborted upload

### ISSUE THREAD

**Issue by veaceslavdoina** [codex-storage/nim-codex#527]
**Describe the bug**
Codex crash when file upload is aborted

**To Reproduce**
 1. Run Codex via Docker Compose with `image: codexstorage/nim-codex:latest`
    <details>
    <summary>docker-compose.yaml</summary>

    ```yaml
    services:
      codex-node1:
        image: codexstorage/nim-codex:latest
        environment:
          - CODEX_LOG_LEVEL=${CODEX_LOG_LEVEL:-TRACE}
          - CODEX_METRICS=${CODEX_METRICS:-false}
          - CODEX_METRICS_ADDRESS=${CODEX_METRICS_ADDRESS:-0.0.0.0}
          - CODEX_METRICS_PORT=${CODEX_METRICS_PORT:-8008}
          - CODEX_DATA_DIR=${CODEX_DATA_DIR:-/datadir}
          - CODEX_LISTEN_ADDRS=${CODEX_LISTEN_ADDRS:-/ip4/0.0.0.0/tcp/2345}
          - CODEX_NAT=${CODEX_NAT:-10.0.0.10}
          - CODEX_DISC_IP=${CODEX_DISC_IP:-0.0.0.0}
          - CODEX_DISC_PORT=${CODEX_DISC_PORT:-8090}
          - CODEX_NET_PRIVKEY=${CODEX_NET_PRIVKEY:-key}
          # - CODEX_BOOTSTRAP_NODE=${CODEX_BOOTSTRAP_NODE}
          - CODEX_MAX_PEERS=${CODEX_MAX_PEERS:-160}
          - CODEX_AGENT_STRING=${CODEX_AGENT_STRING:-Codex}
          - CODEX_API_BINDADDR=${CODEX_API_BINDADDR:-127.0.0.1}
          - CODEX_API_PORT=${CODEX_API_PORT:-8080}
          - CODEX_REPO_KIND=${CODEX_REPO_KIND:-fs}
          - CODEX_STORAGE_QUOTA=${CODEX_STORAGE_QUOTA:-8589934592}
          - CODEX_BLOCK_TTL=${CODEX_BLOCK_TTL:-24h}
          - CODEX_BLOCK_MI=${CODEX_BLOCK_MI:-10000}
          - CODEX_BLOCK_MN=${CODEX_BLOCK_MN:-10000}
          - CODEX_CACHE_SIZE=${CODEX_CACHE_SIZE:-0}
          - CODEX_PERSISTENCE=${CODEX_PERSISTENCE:-false}
          - CODEX_ETH_PROVIDER=${CODEX_ETH_PROVIDER:-ws://localhost:8545}
          # - CODEX_ETH_ACCOUNT=${CODEX_ETH_ACCOUNT}
          # - CODEX_MARKETPLACE_ADDRESS=${CODEX_MARKETPLACE_ADDRESS:-0x59b670e9fA9D0A427751Af201D676719a970857b}
          - CODEX_VALIDATOR=${CODEX_VALIDATOR:-false}
          - CODEX_VALIDATOR_MAX_SLOTS=${CODEX_VALIDATOR_MAX_SLOTS:-1000}
        ports:
          - 8080:8080/tcp # REST API
          - 8008:8008/tcp # Metrics
          - 2345:2345/tcp # libp2p
          - 8090:8090/udp # DHT discovery
        volumes:
          - ./datadir:/datadir
        networks:
          - codex
    networks:
      codex:
        driver: bridge
    ```

    </details>

 2. Use [100MB.bin](https://speed.hetzner.de/100MB.bin) file
 3. Start upload with 5 seconds duration
    ```shell
    timeout 5 curl -X POST localhost:8080/api/codex/v1/upload \
      -H "Content-Type: application/octet-stream" \
      -H "Expect: 100-continue" -T 100MB.bin
    ```
 4. See the error
    <details>
    </summary>crash output</summary>

    ```shell
    codex-codex-node1-1  | TRC 2023-08-24 10:33:40.898+00:00 Provided to nodes                          topics="codex discovery" tid=1 nodes=1
    codex-codex-node1-1  | TRC 2023-08-24 10:33:40.898+00:00 Advertising block                          topics="codex discoveryengine" tid=1 cid=zb2*WWb46N inflight=1
    codex-codex-node1-1  | TRC 2023-08-24 10:33:40.899+00:00 Advertised block                           topics="codex discoveryengine" tid=1 cid=zb2*WWb46N inflight=0
    codex-codex-node1-1  | TRC 2023-08-24 10:33:40.900+00:00 Reading bytes from reader                  topics="libp2p asyncstreamwrapper" tid=1 bytes=60992
    codex-codex-node1-1  | TRC 2023-08-24 10:33:40.900+00:00 Reading bytes from reader                  topics="libp2p asyncstreamwrapper" tid=1 bytes=56896
    codex-codex-node1-1  | TRC 2023-08-24 10:33:40.901+00:00 Reading bytes from reader                  topics="libp2p asyncstreamwrapper" tid=1 bytes=52800
    codex-codex-node1-1  | TRC 2023-08-24 10:33:40.901+00:00 Reading bytes from reader                  topics="libp2p asyncstreamwrapper" tid=1 bytes=48704
    codex-codex-node1-1  | TRC 2023-08-24 10:33:40.901+00:00 Reading bytes from reader                  topics="libp2p asyncstreamwrapper" tid=1 bytes=44608
    codex-codex-node1-1  | TRC 2023-08-24 10:33:40.902+00:00 Reading bytes from reader                  topics="libp2p asyncstreamwrapper" tid=1 bytes=40512
    codex-codex-node1-1  | TRC 2023-08-24 10:33:40.902+00:00 Reading bytes from reader                  topics="libp2p asyncstreamwrapper" tid=1 bytes=36416
    codex-codex-node1-1  | TRC 2023-08-24 10:33:40.904+00:00 CatchableError exception                   topics="codex node" tid=1 exc="Stream boundary is not reached yet"
    codex-codex-node1-1  | /src/codex.nim(131)      codex
    codex-codex-node1-1  | /src/vendor/nim-chronos/chronos/asyncloop.nim(263) poll
    codex-codex-node1-1  | /src/vendor/nim-chronos/chronos/asyncfutures2.nim(318) futureContinue
    codex-codex-node1-1  | /src/codex/chunker.nim(95) reader
    codex-codex-node1-1  | [[reraised from:
    codex-codex-node1-1  | /src/codex.nim(131)      codex
    codex-codex-node1-1  | /src/vendor/nim-chronos/chronos/asyncloop.nim(263) poll
    codex-codex-node1-1  | /src/vendor/nim-chronos/chronos/asyncfutures2.nim(318) futureContinue
    codex-codex-node1-1  | /src/vendor/nim-chronos/chronos/asyncmacro2.nim(213) reader
    codex-codex-node1-1  | ]]
    codex-codex-node1-1  | [[reraised from:
    codex-codex-node1-1  | /src/codex.nim(131)      codex
    codex-codex-node1-1  | /src/vendor/nim-chronos/chronos/asyncloop.nim(263) poll
    codex-codex-node1-1  | /src/vendor/nim-chronos/chronos/asyncfutures2.nim(355) futureContinue
    codex-codex-node1-1  | ]]
    codex-codex-node1-1  | Error: unhandled exception: Stream boundary is not reached yet [Defect]
    codex-codex-node1-1 exited with code 1
    ```
    </details>

**Expected behavior**
Codex should continue to work even if upload was aborted, intentionally or because of the network failure.

**Screenshots**
<img width="1173" alt="Screenshot 2023-08-24 at 13 36 40" src="https://github.com/codex-storage/nim-codex/assets/20563034/3584ff37-77e7-4d1f-b440-0a02be915587">

**Environment**
```
docker run --rm codexstorage/nim-codex:latest codex --version

Codex version:  untagged build
Codex revision: f10c3f
Nim Compiler Version 1.6.14 [Linux: amd64]
```
