### ISSUE TITLE
Run 100 nodes on one public IP -- DHT limitation was dropped

### ISSUE THREAD

**Issue by emizzle** [codex-storage/nim-codex#823]

**Comment by veaceslavdoina** [comment]
### Solution

 1. [Install Docker](https://docs.docker.com/engine/install/)

 2. Create files in a directory
    ```shell
    mkdir /opt/codex
    cd /opt/codex
    ```

    <details>
    <summary>bootstrap.yaml</summary>

    ```yaml
    # vi bootstrap.yaml
    services:
      codex:
        image: ${IMAGE:-codexstorage/nim-codex:0.1.2}
        container_name: ${CONTAINER_NAME:-codex-bootstrap}
        hostname: ${HOSTNAME:-codex-bootstrap}
        restart: always
        command:
          - codex
        environment:
          - CODEX_DATA_DIR=/data
          - CODEX_LOG_LEVEL=TRACE;warn:discv5,providers,manager,cache;warn:libp2p,multistream,switch,transport,tcptransport,semaphore,asyncstreamwrapper,lpstream,mplex,mplexchannel,noise,bufferstream,mplexcoder,secure,chronosstream,connection,connmanager,websock,ws-session
          - CODEX_METRICS=${CODEX_METRICS}
          - CODEX_METRICS_ADDRESS=${CODEX_METRICS_ADDRESS}
          - CODEX_METRICS_PORT=${CODEX_METRICS_PORT}
          - CODEX_API_BINDADDR=0.0.0.0
          - CODEX_API_PORT=${CODEX_API_PORT}
          - CODEX_LISTEN_ADDRS=/ip4/0.0.0.0/tcp/${CODEX_TRANSPORT_PORT}
          - CODEX_DISC_PORT=${CODEX_DISCOVERY_PORT}
          - CODEX_NAT=${CODEX_NAT:-127.0.0.1}
        # ports:
        #   - ${CODEX_METRICS_PORT}:${CODEX_METRICS_PORT}/tcp     # Metrics
        #   - ${CODEX_API_PORT}:${CODEX_API_PORT}/tcp             # API
        #   - ${CODEX_DISCOVERY_PORT}:${CODEX_DISCOVERY_PORT}/udp # Discovery
        #   - ${CODEX_TRANSPORT_PORT}:${CODEX_TRANSPORT_PORT}/tcp # Transport
        volumes:
          - ./codex-data:/data
        logging:
          driver: json-file
          options:
            max-size: 100m
            max-file: 3
        network_mode: host
    #     networks:
    #       - codex

    # networks:
    #   codex:
    #     name: codex
    #     driver: bridge
    ```
    </details>


    <details>
    <summary>storage.yaml</summary>

    ```yaml
    # vi storage.yaml
    services:
      codex:
        image: ${IMAGE:-codexstorage/nim-codex:0.1.2}
        container_name: ${CONTAINER_NAME:-codex-storage}
        hostname: ${HOSTNAME:-codex-storage}
        restart: always
        command:
          - codex
          - persistence
        environment:
          - CODEX_DATA_DIR=/data
          - CODEX_LOG_LEVEL=TRACE;warn:discv5,providers,manager,cache;warn:libp2p,multistream,switch,transport,tcptransport,semaphore,asyncstreamwrapper,lpstream,mplex,mplexchannel,noise,bufferstream,mplexcoder,secure,chronosstream,connection,connmanager,websock,ws-session
          - CODEX_METRICS=${CODEX_METRICS}
          - CODEX_METRICS_ADDRESS=${CODEX_METRICS_ADDRESS}
          - CODEX_METRICS_PORT=${CODEX_METRICS_PORT}
          - CODEX_API_PORT=${CODEX_API_PORT}
          - CODEX_API_BINDADDR=0.0.0.0
          - CODEX_LISTEN_ADDRS=/ip4/0.0.0.0/tcp/${CODEX_TRANSPORT_PORT}
          - CODEX_DISC_PORT=${CODEX_DISCOVERY_PORT}
          - CODEX_NAT=${CODEX_NAT:-127.0.0.1}
          - CODEX_BLOCK_TTL=${CODEX_BLOCK_TTL:-1h}
          - CODEX_ETH_PROVIDER=${CODEX_ETH_PROVIDER:-https://rpc.testnet.codex.storage}
          - PRIV_KEY=${PRIV_KEY}
          - CODEX_MARKETPLACE_ADDRESS=${CODEX_MARKETPLACE_ADDRESS:-0x9C88D67c7C745D2F0A4E411c18A6a22c15b37EaA}
          - CODEX_BOOTSTRAP_NODE=${CODEX_BOOTSTRAP_NODE}
        # ports:
        #   - ${CODEX_METRICS_PORT}:${CODEX_METRICS_PORT}/tcp     # Metrics
        #   - ${CODEX_API_PORT}:${CODEX_API_PORT}/tcp             # API
        #   - ${CODEX_DISCOVERY_PORT}:${CODEX_DISCOVERY_PORT}/udp # Discovery
        #   - ${CODEX_TRANSPORT_PORT}:${CODEX_TRANSPORT_PORT}/tcp # Transport
        volumes:
          - ./codex-data:/data
        logging:
          driver: json-file
          options:
            max-size: 100m
            max-file: 3
        network_mode: host
        # networks:
        #   - codex

    # networks:
    #   codex:
    #     name: codex
    #     external: true
    ```
    </details>

    <details>
    <summary>run.sh</summary>

    ```shell
    # vi run.sh

    # Variables
    codex_image="${codex_image:-codexstorage/nim-codex:0.1.2}"
    storage_nodes="${storage_nodes:-001..100}"
    storage_block_ttl="${storage_block_ttl:-1h}"
    nat_ip="${nat_ip:-127.0.0.1}"
    base_dir="${base_dir:-.}"
    docker_compose="docker-compose.yaml"
    env_file=".env"


    # Bootstrap
    ## Define
    bootstrap_compose="bootstrap.yaml"
    bootstrap_suffix="bootstrap"
    bootstrap_dir="${base_dir}/${bootstrap_suffix}"
    bootstrap_env_file="${bootstrap_dir}/${env_file}"
    bootstrap_container_name="codex-${bootstrap_suffix}"
    bootstrap_hostname="${bootstrap_container_name}"
    bootstrap_nat="${nat_ip}"
    bootstrap_metrics="true"
    bootstrap_metrics_address="0.0.0.0"
    bootstrap_metrics_port=6000
    bootstrap_api_port=7000
    bootstrap_discovery_port=8000
    bootstrap_transport_port=9000

    ## Prepare
    mkdir -p ${bootstrap_dir}
    cp ${bootstrap_compose} ${bootstrap_dir}/${docker_compose}
    echo "IMAGE=${codex_image}" >${bootstrap_env_file}
    echo "CONTAINER_NAME=${bootstrap_container_name}" >>${bootstrap_env_file}
    echo "HOSTNAME=${bootstrap_hostname}" >>${bootstrap_env_file}
    echo "CODEX_METRICS=${bootstrap_metrics}" >>${bootstrap_env_file}
    echo "CODEX_METRICS_ADDRESS=${bootstrap_metrics_address}" >>${bootstrap_env_file}
    echo "CODEX_METRICS_PORT=${bootstrap_metrics_port}" >>${bootstrap_env_file}
    echo "CODEX_API_PORT=${bootstrap_api_port}" >>${bootstrap_env_file}
    echo "CODEX_DISCOVERY_PORT=${bootstrap_discovery_port}" >>${bootstrap_env_file}
    echo "CODEX_TRANSPORT_PORT=${bootstrap_transport_port}" >>${bootstrap_env_file}
    echo "CODEX_NAT=${bootstrap_nat}" >>${bootstrap_env_file}

    ## Run
    cd ${bootstrap_dir}
    docker compose up -d
    cd ..

    ## Wait for API
    WAIT=60
    SECONDS=0
    while (( SECONDS < WAIT )); do
      staus=$(curl -m 2 -s ${bootstrap_nat}:${bootstrap_api_port}/api/codex/v1/debug/info -o /dev/null -w %{http_code})
      [[ ${staus} -eq 200 ]] && break
      echo "Wait for bootstrap API - `date`"
      sleep 1
    done


    # Storage
    storage_spr=$(curl -s ${bootstrap_nat}:${bootstrap_api_port}/api/codex/v1/debug/info | jq -r '.spr')
    storage_compose="storage.yaml"
    storage_priv_key="0xf780d9aa4c2738c9d8607314a84cf286a94a06e8b9b55e6e8a7f26e8231cc3e5"

    for node in $(eval echo {$storage_nodes}); do
      ## Define
      storage_suffix="storage-${node}"
      storage_dir="${base_dir}/${storage_suffix}"
      storage_env_file="${storage_dir}/${env_file}"
      storage_container_name="codex-${storage_suffix}"
      storage_hostname="${storage_container_name}"
      storage_nat="${nat_ip}"
      storage_metrics="true"
      storage_metrics_address="0.0.0.0"
      storage_metrics_port=6${node}
      storage_api_port=7${node}
      storage_discovery_port=8${node}
      storage_transport_port=9${node}


      ## Prepare
      mkdir -p ${storage_dir}
      cp ${storage_compose} ${storage_dir}/${docker_compose}
      echo "IMAGE=${codex_image}" >${storage_env_file}
      echo "CONTAINER_NAME=${storage_container_name}" >>${storage_env_file}
      echo "HOSTNAME=${storage_hostname}" >>${storage_env_file}
      echo "CODEX_METRICS=${storage_metrics}" >>${storage_env_file}
      echo "CODEX_METRICS_ADDRESS=${storage_metrics_address}" >>${storage_env_file}
      echo "CODEX_METRICS_PORT=${storage_metrics_port}" >>${storage_env_file}
      echo "CODEX_API_PORT=${storage_api_port}" >>${storage_env_file}
      echo "CODEX_DISCOVERY_PORT=${storage_discovery_port}" >>${storage_env_file}
      echo "CODEX_TRANSPORT_PORT=${storage_transport_port}" >>${storage_env_file}
      echo "CODEX_NAT=${storage_nat}" >>${storage_env_file}
      echo "CODEX_BLOCK_TTL=${storage_block_ttl}" >>${storage_env_file}
      echo "PRIV_KEY=${storage_priv_key}" >>${storage_env_file}
      echo "CODEX_BOOTSTRAP_NODE=${storage_spr}" >>${storage_env_file}

      ## Run
      cd ${storage_dir}
      docker compose up -d
      cd ..
    done
    ```
    </details>

    <details>
    <summary>upload_download.sh</summary>

    ```shell
    # vi upload_download.sh

    # Variables
    storage_nodes="${storage_nodes:-001..100}"
    file_size="${file_size:-10M}" # 10M, 100M, 1G
    file_name="${file_size}.bin"

    while true; do
      # Generate
      dd if=/dev/urandom of="${file_name}" bs="${file_size}" count=1 2>/dev/null


      # Start
      echo "Start - `date`"

      # Uploader
      uploader=$(printf "%s\n" $(eval echo {$storage_nodes}) | shuf -n 1)

      # Upload
      SECONDS=0
      echo "Upload to node ${uploader} - ${file_name}"
      cid=$(curl -X POST \
        http://localhost:7${uploader}/api/codex/v1/data \
        --header 'Content-Type: application/octet-stream' \
        -T "${file_name}")

      if [[ "$(uname)" == "Darwin" ]]; then
        upload_duration=$(date -u -r "${SECONDS}" "+%M:%S")
      else
        upload_duration=$(date -d@"${SECONDS}" "+%M:%S")
      fi

      # Downloader
      while true; do
        downloader=$(printf "%s\n" $(eval echo {$storage_nodes}) | shuf -n 1)
        [[ "${downloader}" != "${uploader}" ]] && break
      done

      # Download
      SECONDS=0
      echo "Download from node ${downloader} - ${cid}"
      curl -o "${cid}" "http://localhost:7${downloader}/api/codex/v1/data/${cid}/network"

      if [[ "$(uname)" == "Darwin" ]]; then
        download_duration=$(date -u -r "${SECONDS}" "+%M:%S")
      else
        download_duration=$(date -d@"${SECONDS}" "+%M:%S")
      fi

      # Compare
      diff "${file_name}" "${cid}" && result="\x1B[32m Files are identical \x1B[0m" || result="\x1B[01;91m Files are different \x1B[0m"

      # Cleanup
      rm -f "${file_name}" "${cid}"

      # Report
      echo -e "\n"
      echo "Uploader node-${uploader} - ${upload_duration}"
      echo "Downloader node-${downloader} - ${download_duration}"
      echo -e "Result - ${result}"
      echo "File ${file_name} / ${cid}"
      echo -e "----------------------------------------\n"
    done
    ```
    </details>

    <details>
    <summary>stop.sh</summary>

    ```shell
    # vi stop.sh

    # Variables
    base_dir="${base_dir:-.}"
    storage_nodes="${storage_nodes:-001..100}"


    # Storage
    ## Stop
    for node in $(eval echo {$storage_nodes}); do
      storage_suffix="storage-${node}"
      storage_dir="${base_dir}/${storage_suffix}"

      cd ${storage_dir}
      docker compose down
      cd ..
    done


    # Bootstrap
    bootstrap_suffix="bootstrap"
    bootstrap_dir="${base_dir}/${bootstrap_suffix}"

    ## Stop
    cd ${bootstrap_dir}
    docker compose down
    cd ..
    ```
    </details>

 3. Define variables
    ```shell
    export codex_image="codexstorage/nim-codex:0.1.2"
    export storage_nodes="001..100"
    export storage_block_ttl="30m"
    # export nat_ip="127.0.0.1"
    export nat_ip=$(curl -s ip.codex.storage)
    export file_size="10M"
    export base_dir="."
    ```

 4. Run nodes
    ```shell
    time bash run.sh

    # real	0m24.943s
    ```

 5. Run upload/download
    ```
    bash upload_download.sh

    # Ctrl + C
    ```

 6. Stop nodes
    ```shell
    time bash stop.sh

    # real	4m32.879s
    ```

### Troubleshooting

```shell
# Kill all codex-storage containers
docker ps | awk '/codex-storage/ {print $1}' | while read id; do docker kill $id; done
```
